export const types = {
    TIME_MACHINE_INIT: 'TIME_MACHINE_INIT',
    SET_MINUTES: 'SET_MINUTES',
    SET_HOURS: 'SET_HOURS',
    SET_DAYS: 'SET_DAYS',
    SET_YEARS: 'SET_YEARS',
    CLEAR_HOURS_TIMER: 'CLEAR_HOURS_TIMER'
};
