export const types = {
    START_GAME_FORM_UPDATE:     'START_GAME_FORM_UPDATE',
    START_LOADING_GAME:         'LOADING_GAME_UPDATE',
    LOADING_GAME_UPDATE:        'LOADING_GAME_UPDATE',
    LOADING_GAME_TITLE_UPDATE:  'LOADING_GAME_TITLE_UPDATE',
    LOADING_GAME_COMPLETE:      'LOADING_GAME_UPDATE',
    MAP_LOADED:                 'MAP_LOADED',
    MAP_LOADING:                'MAP_LOADING',
    INIT_GAME:                  'INIT_GAME',
    START_GAME:                 'START_GAME',
    STOP_GAME:                  'STOP_GAME',
    TOGGLE_PAUSE_GAME:          'TOGGLE_PAUSE_GAME',
    GAMEOVER:                   'GAMEOVER',
    WIN_GAME:                   'WIN_GAME',
    EXIT_GAME:                  'EXIT_GAME',
    ERROR_GAME:                 'ERROR_GAME',
    SAVE_GAME:                  'SAVE_GAME',
    LOAD_GAME_SAVE:             'LOAD_GAME_SAVE',
    SET_VOLUME:                 'SET_VOLUME',
    TOGGLE_GAME_MENU_ESC:       'TOGGLE_GAME_MENU_ESC',
    SINTHESIZE_NEW_GAME:        'SINTHESIZE_NEW_GAME',
    START_OR_LOAD_MODAL_CLOSE:  'START_OR_LOAD_MODAL_CLOSE',
};