export const types = {
    MAP_CLICK:          'MAP_CLICK',
    MAP_INCREASE:       'MAP_INCREASE',
    MAP_DECREASE:       'MAP_DECREASE',
    MAP_IS_DRAGGABLE:   'MAP_IS_DRAGGABLE',
    MAP_NO_DRAGGABLE:   'MAP_NO_DRAGGABLE',
    MAP_DRAG_START:     'MAP_DRAG_START',
    MAP_DRAG_MOVE:      'MAP_DRAG_MOVE',
    MAP_DRAG_STOP:      'MAP_DRAG_STOP',
};