export const types = {
    UNIT_CREATED:           'UNIT_CREATED',
    UNITS_LOAD:           'UNITS_LOAD',
    UNIT_KILLED:            'UNIT_KILLED',
    UNIT_DIED:              'UNIT_DIED',

    UNIT_STATS_TOGGLE:      'UNIT_STATS_TOGGLE',
    
    UNIT_INIT_POSITION:     'UNIT_INIT_POSITION',
    UNIT_SET_PATH_POINT:    'UNIT_SET_PATH_POINT',
    UNIT_SET_PATH:          'UNIT_SET_PATH',
    UNIT_START_WALKING:     'UNIT_START_WALKING',
    UNIT_STOP_WALKING:      'UNIT_STOP_WALKING',
    UNIT_WALKING:           'UNIT_WALKING',

    UNIT_GET_TASK:          'UNIT_GET_TASK',
    UNIT_TASK_SEARCH:       'UNIT_TASK_SEARCH',
    UNIT_TASK_PERFORMS:     'UNIT_TASK_PERFORMS',
    UNIT_TASK_COMPLETE:     'UNIT_TASK_COMPLETE',

    UNIT_LEVEL_UP:          'UNIT_LEVEL_UP',
    UNIT_LEVEL_UP_SKILL:    'UNIT_LEVEL_UP_SKILL',

    UNIT_START_REST:        'UNIT_START_REST',
    UNIT_STOP_REST:         'UNIT_STOP_REST',
    UNIT_START_SICK:        'UNIT_START_SICK',
    UNIT_STOP_SICK:         'UNIT_STOP_SICK',
    UNIT_START_REPAIR:      'UNIT_START_REPAIR',
    UNIT_STOP_REPAIR:       'UNIT_STOP_REPAIR',

    UNIT_SPOTTED_ENEMY:     'UNIT_SPOTTED_ENEMY',
    UNIT_ATTAK:             'UNIT_ATTAK',
    UNIT_TAKES_DAMAGE:      'UNIT_TAKES_DAMAGE',

    UNIT_PUT_ITEM:          'UNIT_PUT_ITEM',
    UNIT_THROWS_ITEM:       'UNIT_THROWS_ITEM',
    UNIT_WEAR_ITEM:         'UNIT_WEAR_ITEM',
    UNIT_USE_ITEM:          'UNIT_USE_ITEM',

};