export const types = {
    TASK_ADD:           'TASK_ADD',
    TASK_COMPLETE:          'TASK_COMPLETE',
    TASK_ACCEPTED:      'TASK_ACCEPTED',
    TASK_IN_PROGRESS:   'TASK_IN_PROGRESS',
    TASK_PAUSED:        'TASK_PAUSED',
    TASK_CONTINUED:     'TASK_CONTINUED',
    TASK_DISTROY:       'TASK_DISTROY',
};